[workspace]
resolver = "2"
members = [
  "crates/anicargo-bangumi",
  "crates/anicargo-config",
  "crates/anicargo-library",
  "crates/anicargo-media",
  "crates/anicargo-qbittorrent",
  "crates/anicargo-cli",
  "crates/anicargo-api",
]
